LQ45 = (
    "AADI ADMR ADRO AKRA AMMN AMRT ANTM ASII BBCA BBNI BBRI BBTN BMRI "
    "BRPT BUMI CPIN CUAN DEWA EMTK ESSA EXCL GOTO HRTA ICBP INCO INDF "
    "INDY INKP ISAT ITMG JPFA KLBF MAPI MBMA MDKA MEDC NCKL PGAS PGEO "
    "PTBA SCMA TLKM UNTR UNVR WIFI"
).split()

BANKING = (
    "AGRO AGRS ARTO BABP BACA BBCA BBHI BBKP BBMD BBNI BBRI BBSI BBTN "
    "BBYB BCIC BDMN BEKS BGTG BINA BJBR BJTM BKSW BMAS BMRI BNBA BNGA "
    "BNII BNLI BRIS BSIM BSWD BTPN BTPS BVIC DNAR INPC MASB MAYA MCOR "
    "MEGA NISP NOBU PNBN PNBS SDRA AMAR BANK"
).split()

CONGLOMERATE = (
    "BREN TPIA PTRO CDIA ENRG VKTR VIVA MDIA ALII PGUN JARR DSSA DCII"
).split()

FOCUSED_UNIVERSE = tuple(dict.fromkeys(LQ45 + BANKING + CONGLOMERATE))
FOCUSED_UNIVERSE_SET = set(FOCUSED_UNIVERSE)

if len(FOCUSED_UNIVERSE) != 100:
    raise RuntimeError(
        f"Focused universe harus 100 saham, sekarang {len(FOCUSED_UNIVERSE)}"
    )
